name: Castle Quest
favicon: null
layout_spectrum: 0.5078404098749161
typography_spectrum: 0.7360305327456445
title: Strattonia plans to Tour Europe
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#80744e'
    - '#335861'
    - '#fafafa'
    - '#789ea7'
  brandStrength: 0.4889501887373626
  lightness: 0.557927095098421
  saturation: 0.051677277544513345
  rhythmicContrast: 0.25312887341715395
purpose: []
