name: Castle Quest
favicon: null
layout_spectrum: 1
typography_spectrum: 0.58111
title: Strattonia Castles
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#980606'
    - '#fefefe'
    - '#525252'
    - '#b8b8b8'
  brandStrength: 0.1875
  lightness: 0.125
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
