name: Castle Quest
favicon: null
layout_spectrum: 0.50624
typography_spectrum: 0.14657
title: The Strattonian Castles
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#3c0000'
    - '#9f0007'
    - '#0c4b7b'
    - '#286691'
  brandStrength: 0.1875
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
