name: Castle Quest
favicon: null
layout_spectrum: 0.50624
typography_spectrum: 0.58111
title: Strattonia Castles
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030303'
    - '#414048'
    - '#77767e'
    - '#730200'
    - '#f7c1bf'
  brandStrength: 0.6875
  lightness: 0.1875
  saturation: 0.6875
  rhythmicContrast: 0.25
purpose: []
