name: Castle Quest
favicon: null
layout_spectrum: 0.50624
typography_spectrum: 0.58111
title: Strattonia Castles
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#061b54'
    - '#163590'
    - '#478bec'
    - '#c3ecfd'
  brandStrength: 0.6875
  lightness: 0
  saturation: 0.875
  rhythmicContrast: 0
purpose: []
