name: Castle Quest
favicon: null
layout_spectrum: 0.73939
typography_spectrum: 0.6268
title: Strattonia Castles
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#80744e'
    - '#335861'
    - '#fafafa'
    - '#789ea7'
  brandStrength: 0.5
  lightness: 0.125
  saturation: 0.125
  rhythmicContrast: 1
purpose: []
